#!/bin/sh
#
# AUTHOR: fmilani
#
# DATE: Thu Dec 07 2023
#
# DESC: Elvi to search Confluence
# elvis: confluence	-- Search Confluence (https://evoluservices.atlassian.net/wiki)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search Confluence (https://evoluservices.atlassian.net/wiki/)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://evoluservices.atlassian.net/wiki/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://evoluservices.atlassian.net/wiki/search?text=${escaped_args}"
fi
