#!/bin/sh
#
# AUTHOR: fmilani
#
# DATE: Sat May 22 2021
#
# DESC: Elvi to search Dicio
# elvis: dicio		-- Search Dicio (www.dicio.com.br)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search Dicio (www.dicio.com.br) for words
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.dicio.com.br/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.dicio.com.br/pesquisa.php?q=${escaped_args}"
fi
