#!/bin/sh
#
# AUTHOR: fmilani
#
# DATE: Sat May 22 2021
#
# DESC: Elvi to search Gerrit
# elvis: gerrit		-- Search Gerrit (gerrit.evoluservices.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search Gerrit (gerrit.evoluservices.com) for changes
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://gerrit.evoluservices.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://gerrit.evoluservices.com/q/${escaped_args}"
fi
