#!/bin/sh
#
# AUTHOR: fmilani
#
# DATE: Sat Feb 19 2022
#
# DESC: Elvi to search movies and tv shows on justwatch.com
# elvis: justwatch	-- Search on JustWatch (justwatch.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search JustWatch (justwatch.com) for movies and tv shows
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.justwatch.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.justwatch.com/br/busca?q=${escaped_args}"
fi
