#!/bin/sh
#
# AUTHOR: fmilani
#
# DATE: Wed Dec 27 2023
#
# DESC: Elvi to search google maps
# elvis: maps	    -- Search google maps
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search google maps for destination
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.google.com/maps/dir/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.google.com/maps/dir//${escaped_args}"
fi
