#! /bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

GAP_SIZE=8
POLYBAR_HEIGHT=32
POLYBAR_TOP_OFFSET=8
BORDER_WIDTH=2

bspc config window_gap $GAP_SIZE
# bspc config top_padding $(($POLYBAR_HEIGHT + $POLYBAR_GAP)) # on HiDPI
bspc config top_padding $(($POLYBAR_HEIGHT + $POLYBAR_TOP_OFFSET))
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

#Various settings
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
## Honor size hints: do not make windows smaller than they wish to be
#bspc config honor_size_hints true 

##Color settings
bspc config focused_border_color "#ddb6f2"
bspc config normal_border_color "#1e1e2e"
#"#000000"
bspc config presel_feedback_color "#1ABB9B"
#"#8F3724"
bspc config border_width "$BORDER_WIDTH"

bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true #Some keybindings automatically enable and disable this setting

#Settings for manual splitting
bspc config split_ratio         0.5

setup-workspaces &

###This creates and names desktops for multiple monitors.
# workspaces_multimonitor &

windowwidth=1280
windowheight=720
screenwidth=$(xdpyinfo | awk -F'[ x]+' '/dimensions:/{print $3}')
screenheight=$(xdpyinfo | awk -F'[ x]+' '/dimensions:/{print $4}')
windowx=$(("$screenwidth"-"$windowwidth"-2*"$GAP_SIZE"))
windowy=$(("$screenheight"-"$windowheight"-2*"$GAP_SIZE"))
bspc rule -a mpv:streaming state=floating sticky=on rectangle="$windowwidth"x"$windowheight"+"$windowx"+"$windowy"

bspc rule -a mpv state=floating
bspc rule -a screenkey --unmanage
bspc rule -a gcolor2 state=floating center=true
bspc rule -a libreoffice state=tiled
bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a '*:soffice' state=tiled
bspc rule -a discord desktop=8
bspc rule -a Slack desktop=9
bspc rule -a tmux follow=on focus=on desktop=0
bspc rule -a 'firefox:Toolkit' state=floating rectangle=1280x720+0+0
bspc rule -a 'Google-chrome:crx_bdpgikbljlobeaeggalahjcnlgkhlfab' desktop=1

# scratchpad_width=$(("$screenwidth"-2*"$BORDER_WIDTH"))
# scratchpad_height=1000
# bspc rule -a scratchpad sticky=on state=floating hidden=on rectangle="$scratchpad_width"x"$scratchpad_height"+0+0
bspc rule -a scratchpad sticky=on state=floating hidden=on

bspc rule -a feh state=floating

##  Autogap adjusts windowgap automatically according to the number of
##  windows on the desktop. Using it disables negative window gap.
# autogap &

##  This script balances all windows when new one is spawned 
#euclid_balancer &

##Edge-switcher switches to next workspace when moves moves to the 
##edge of the monitor (behavior similar to enlightenment)
#edge-switcher &

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
bspc config external_rules_command /usr/bin/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command /usr/bin/adjust-new-window
# bspc config external_rules_command /home/felipe/.bin/first_empty_desktop

##Autostart apps
~/.config/polybar/launch
scratchpad silent &

# feh --bg-fill ~/Pictures/Awesome_Bridge_11658x6112.png
feh --bg-fill ~/Pictures/wallpaper.png

# Alter compton settings if using intel graphics
GRAPHIC_CARD=$(lspci | grep -i "vga" | sed 's/.*://' | sed 's/(.*//' | sed 's/^[ \t]*//')
if [[ $(echo $GRAPHIC_CARD | grep -i 'intel\|lenovo') != "" ]]; then MCODE='initrd=\intel-ucode.img'
  sed -i 's/"xrender"/"glx"/' ~/.config/compton.conf
  grep -q 'vsync = "opengl-swc";' ~/.config/compton.conf || echo 'vsync = "opengl-swc";' >> ~/.config/compton.conf
fi
