#!/usr/bin/env bash

[[ -z "$ROFI_OUTSIDE" ]] && echo "This scripts is meant to run on rofi custom mode" && exit -1

NEW_SESSION_OPTION="Create new session "
if [[ -z "$@" ]]
then
  open_sessions=$(tmux list-windows -a -F "#S:#W" 2>/dev/null)
  starter_scripts=$(ls ~/.bin/tmux-* | grep -v tmux-launcher | xargs -n 1 basename | cut -d'-' -f 2-)
  unopened_starters=$(comm -13 <(echo "$open_sessions") <(echo "$starter_scripts"))
  options=$([[ -n $open_sessions ]] && echo -e "$open_sessions\n$unopened_starters" || echo "$unopened_starters")
  echo -e "$options\n$NEW_SESSION_OPTION"
else
  new_session_name=$(echo "$@" | sed -r "s/${NEW_SESSION_OPTION}(.*)/\1/g")
  coproc ( tmux-launcher "$new_session_name" > /dev/null 2>&1 )
fi
