#!/bin/bash

[[ -z "$ROFI_OUTSIDE" ]] && echo "This scripts is meant to run on rofi custom mode" && exit -1
echo -en "\x00no-custom\x1ftrue\n"
echo -en "\x00markup-rows\x1ftrue\n"

UTILS_FOLDER="$HOME/.bin/utils"
if [[ -z "$@" ]];then
for script in $(ls "$UTILS_FOLDER" | xargs -n 1 basename); do
  rofi_hint=$(grep "#rofi-hint:" "$UTILS_FOLDER/$script")
  if [[ -n "$rofi_hint" ]]; then
    echo "$script" | awk -v rofi_hint="$(echo "$rofi_hint" | rofi-hint-parser)" '{print $1 "\t<span weight=\047light\047 size=\047small\047><i>"rofi_hint"</i></span>"}'
  else
    echo "$script"
  fi
done
else
  coproc ( "$UTILS_FOLDER/$(echo $@ | cut -d' ' -f1)" >/dev/null 2>&1 )
fi

