#!/bin/bash

[[ -z "$ROFI_OUTSIDE" ]] && echo "This scripts is meant to run on rofi custom mode" && exit -1
echo -en "\x00no-custom\x1ftrue\n"

UTILS_FOLDER="$HOME/.bin/utils"
if [[ -z "$@" ]];then
for script in $(ls "$UTILS_FOLDER" | xargs -n 1 basename); do
  echo "$script"
done
else
  coproc ( "$UTILS_FOLDER/$@" >/dev/null 2>&1 )
fi

